---
apiVersion: v1
kind: Secret
metadata:
  name: azdevops-pipeline-auth
data:
  AZP_TOKEN: ****************
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azdevops-pipeline-trigger-auth
spec:
  secretTargetRef:
    - parameter: personalAccessToken
      name: azdevops-pipeline-auth
      key: AZP_TOKEN
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: azdevops-pipelines-scaledobject
spec:
  scaleTargetRef:
    name: azdevops-deployment
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
  - type: azure-pipelines
    metadata:
      poolID: "****************"
      organizationURLFromEnv: "AZP_URL"
    authenticationRef:
     name: azdevops-pipeline-trigger-auth