---
apiVersion: v1
kind: Secret
metadata:
  name: adoagent-off-secret
data:
  AZP_TOKEN: ******************
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adoagent-off-deployment
  labels:
    app: adoagent-off
spec:
  replicas: 1
  template:
    metadata:
      name: adoagent-off-template
      labels:
        app: adoagent-off
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: adoagent-off
        image: xxxxxxxxxxxxxxx.azurecr.io/adoagent:latest
        env:
          - name: AZP_URL
            value: https://dev.azure.com/xxxxxxxxxxxxxxx
          - name: AZP_POOL
            value: AKS
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: adoagent-off-secret
                key: AZP_TOKEN
  selector:
    matchLabels:
      app: adoagent-off