apiVersion: apps/v1
kind: Deployment
metadata:
  name: adoagent-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: adoagent
  template:
    metadata:
      labels:
        app: adoagent
    spec:
      containers:
      - name: adoagent
        image: adoagentacr.azurecr.io/adoagent:latest
        env:
        - name: AZP_URL
          value: https://dev.azure.com/csu-csa-appinnovation
        - name: AZP_TOKEN
          value: XXXXXXXXXXXXXXXX
        - name: AZP_POOL
          value: AKS-pool
