---
apiVersion: v1
kind: Secret
metadata:
  name: adoagent-win-pipeline-auth
data:
  AZP_TOKEN: **************************
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: adoagent-win-pipeline-trigger-auth
spec:
  secretTargetRef:
    - parameter: personalAccessToken
      name: adoagent-win-pipeline-auth
      key: AZP_TOKEN
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: adoagent-win-pipelines-scaledobject
spec:
  scaleTargetRef:
    name: adoagent-win-deployment
  minReplicaCount: 0
  maxReplicaCount: 5
  triggers:
  - type: azure-pipelines
    metadata:
      poolID: "21"
      organizationURLFromEnv: "AZP_URL"
    authenticationRef:
     name: adoagent-win-pipeline-trigger-auth