---
apiVersion: v1
kind: Secret
metadata:
  name: adoagent-win-secret
data:
  AZP_TOKEN: ***************************************
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adoagent-win-deployment
  labels:
    app: adoagent-win
spec:
  replicas: 1
  template:
    metadata:
      name: adoagent-win-template
      labels:
        app: adoagent-win
    spec:
      nodeSelector:
        "kubernetes.io/os": windows
      containers:
      - name: adoagent-win
        image: xxxxxxxxxxxxxx.azurecr.io/adoagent-win:latest
        env:
          - name: AZP_URL
            value: https://dev.azure.com/xxxxxxxxxxxxxx
          - name: AZP_POOL
            value: AKS-win
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: adoagent-win-secret
                key: AZP_TOKEN
  selector:
    matchLabels:
      app: adoagent-win