apiVersion: 2019-12-01
location: westus
name: adoagent-aci
properties:
  containers:
  - name: adoagent
    properties:
      image: adoagentacr.azurecr.io/adoagent:latest
      resources:
        requests:
          cpu: 1
          memoryInGb: 1.5
      environmentVariables:
      - name: AZP_URL
        value: https://dev.azure.com/csu-csa-appinnovation
      - name: AZP_TOKEN
        value: XXXXXXXXXXXXXXXXXXXXXXX
      - name: AZP_POOL
        value: ACI-pool
  osType: Linux
  imageRegistryCredentials:
  - server: adoagentacr.azurecr.io
    username: adoagentacr
    password: XXXXXXXXXXXXXXXX
type: Microsoft.ContainerInstance/containerGroups
