apiVersion: apps/v1
kind: Deployment
metadata:
  name: adoagent-deployment
spec:
  selector:
    matchLabels:
      app: adoagent
  replicas: 2
  template:
    metadata:
      labels:
        app: adoagent
    spec:
      containers:
      - name: adoagent
        image: kledsonhugo/adoagent:latest
        env:
        - name: AZP_URL
          value: https://dev.azure.com/csu-csa-appinnovation
        - name: AZP_TOKEN
          value: XXXXXXXXXXXXXXXXXXXXXXXXXX
        - name: AZP_POOL
          value: Kubernetes-pool
